[package]
name = "nilleniumrust/springshaker"
description = "A camera shaker that uses springs + perlin noise for advanced mathematical calculations, which combine smoothness and efficiency."
version = "1.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "Apache-2.0"
authors = ["Nillenium Rust <nilleniumrust@gmail.com>"]

[dependencies]
Janitor = "howmanysmall/janitor@1.18.3"
Promise = "howmanysmall/typed-promise@4.0.3"